### ISSUE TITLE
Todo List for version 0.4

### ISSUE THREAD

**Issue by chenshenhai** [idrawjs/idraw#53]
## Feature  
* [x] Add `@idraw/renderer` to Deprecate `opts.onlyRender`
* [x] https://github.com/idrawjs/idraw/issues/106
* [x] https://github.com/idrawjs/idraw/issues/111
* [x] Add method `getElementByIndex(i: number)` and  `getElement(uuid: string)` to `@idraw/core` 
* [x] https://github.com/idrawjs/idraw/pull/84
* [x] https://github.com/idrawjs/idraw/issues/111
* [x] Add  return `uuid` from `insertElementBefore`, `insertElementAfter`
* [x] Add  methods there are`insertElementBefore(uuid)` and `insertElementAfter(uuid)`
* [x] Add  methods there are`insertElementBeforeIndex(index)` and `insertElementAfterIndex(index)`
* [x] Watch keyboard to implement copy, cut, paste, delete, undo and redo https://github.com/idrawjs/idraw/issues/74  https://github.com/idrawjs/idraw/pull/75  https://github.com/idrawjs/idraw/pull/81
* [x] Trigger event when select element in onlyrender-status   https://github.com/idrawjs/idraw/pull/54
* [x] Add event named `mouseOverElement` and `mouseLeaveElement`  https://github.com/idrawjs/idraw/pull/54
* [x] Add Method named `exportDataURL` and `saveAsImage` for  export Image
* [x] Set curser default when select locked element  
* [x] Add public function `getScreenTransform()` to `class iDraw` https://github.com/idrawjs/idraw/pull/54
*  ~Refactor: Synchronize `scrollLeft` and `scrollTop`with scale~
* [x] Add  attribute named `invisible` to element data
* [x] Add `doubleClickElement` to `idraw`  https://github.com/idrawjs/idraw/pull/66
* [x] It wraps text when the text string has `\r\n` or `\n` 
* [x] Add `clearOperation` method to idraw for clear all select status https://github.com/idrawjs/idraw/pull/69
* [x] Refactor: add attr `operation: {[key: string]: any}` to `Element` and replace `lock`  https://github.com/idrawjs/idraw/pull/69
* [x] Refactor: add attr `extension: {[key: string]: any}` to  `Element` https://github.com/idrawjs/idraw/pull/69

## BUG
* [x] It can transform element'size  when it was locked
* [x] It can listen `doubleClickElement` when the element is invisible https://github.com/idrawjs/idraw/commit/151fe71e95c10b5a143de38985771a3ff2e032ea
* [x] It can move element when the element is locked
* [x]  The element does not scale as expected when it is rotated https://github.com/idrawjs/idraw/issues/93 https://github.com/idrawjs/idraw/pull/94
* [x] #98 https://github.com/idrawjs/idraw/issues/97
 
## Test
* [x] E2E Test for `@idraw/board` all methods https://github.com/idrawjs/idraw/pull/58 
* [x] E2E Test for `@idraw/util` all methods 

## Documents
* [x] Rename API usage of `scrollX` and `scrollY` to `scrollLeft` and `scrollTop`
* [x] Add Element description
* [x] Add API usage of function `getScreenTranform`
