### ISSUE TITLE
v0.3 roadmap

### ISSUE THREAD

**Issue by chenshenhai** [idrawjs/idraw#86]
## @idraw/kernal

* [ ]  Render eveything width state data
    * [ ] Render element with state data
    * [ ] Render element controller with state data 
* [ ] Listen for complete rendering
    * [ ] Render element with state data
    * [ ] Listen to fully load all asynchronous resources
